server:
  port: 1234
  servlet:
         context-path: /api
  
spring:
     datasource:
          url: jdbc:oracle:thin:@localhost:1521:orcl
          username: system
          password: akash
          driver-class-name: oracle.jdbc.OracleDriver
     jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            

